services:
  - type: web
    name: frejfund
    env: node
    buildCommand: npm install && npm run build
    startCommand: cd .next/standalone && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true 