'use client';
import React, { useState } from 'react';
import { CircularProgressbar, buildStyles } from 'react-circular-progressbar';
import 'react-circular-progressbar/dist/styles.css';
import ActionableInsights from './ActionableInsights';

const getScoreEmoji = (score: number) => {
  if (score >= 75) return '🚀';
  if (score >= 50) return '⭐';
  if (score >= 25) return '💡';
  return '🔨';
};

const getScoreColor = (score: number) => {
  if (score >= 75) return '#10B981';
  if (score >= 50) return '#F59E0B';
  if (score >= 25) return '#EF4444';
  return '#6B7280';
};

const getActionableInsights = (category: any) => {
  // This would be generated by AI based on the actual scores
  const insightMaps: Record<string, any[]> = {
    problemSolution: [
      {
        title: 'Kvantifiera kundens smärta i kronor',
        impact: 'high',
        timeframe: '1-2 veckor',
        description: 'Er lösning adresserar ett problem men saknar konkret data om vad det kostar kunden idag.',
        implementation: [
          'Intervjua 10 befintliga kunder om deras tidsåtgång',
          'Beräkna timkostnad × antal timmar = årlig kostnad',
          'Dokumentera 3-5 konkreta exempel med företagsnamn',
          'Skapa en "ROI-kalkylator" för säljmaterial'
        ],
        expectedResult: 'Öka konvertering med 30-40% genom att visa "Spara 420.000 kr/år" istället för "Spara tid"',
        investorPerspective: 'Investerare vill se att ni förstår kundens ekonomi på djupet. Siffror > känslor.'
      }
    ],
    marketTiming: [
      {
        title: 'Koppla er lösning till makrotrender',
        impact: 'medium',
        timeframe: '1 vecka',
        description: 'Marknaden växer men er koppling till drivande trender är otydlig.',
        implementation: [
          'Lista 3 makrotrender som driver er marknad (AI, reglering, etc)',
          'Hitta 2-3 trovärdiga källor per trend (Gartner, McKinsey)',
          'Skapa en "Why Now" slide med timeline',
          'Koppla varje trend till er lösning specifikt'
        ],
        expectedResult: 'Investerare förstår varför detta är rätt timing och inte bara "nice to have"',
        investorPerspective: 'Vi letar efter företag som surfar på vågor, inte de som försöker skapa dem.'
      }
    ],
    unitEconomics: [
      {
        title: 'Optimera CAC genom produktledd tillväxt',
        impact: 'high',
        timeframe: '3-6 månader',
        description: 'Er CAC på €1000 kan halveras med rätt strategi.',
        implementation: [
          'Bygg en gratis "light version" med begränsningar',
          'Skapa viral loop: varje användare bjuder in 2 kollegor',
          'Automatisera onboarding med produkttours',
          'Mät och optimera varje steg i aktiveringsflödet'
        ],
        expectedResult: 'Sänk CAC till €500, vilket ger LTV:CAC 8:1 och möjliggör aggressiv expansion',
        investorPerspective: 'Företag med CAC < €500 får 3x högre värderingsmultiplar i Series A.'
      }
    ]
  };

  return insightMaps[category] || [];
};

export default function EnhancedMobileResult({ data }: { data: any }) {
  const [activeTab, setActiveTab] = useState<'overview' | 'details' | 'actions'>('overview');
  const [expandedCategory, setExpandedCategory] = useState<string | null>(null);

  const categories = Object.entries(data.categories);

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900/10 to-slate-900">
      {/* Mobile Sticky Header */}
      <div className="sticky top-20 z-40 bg-slate-900/95 backdrop-blur-lg border-b border-white/10">
        <div className="px-4 py-3">
          <div className="flex items-center justify-between">
            <div className="flex-1">
              <h1 className="text-lg font-bold text-white">Investeringsanalys</h1>
              <p className="text-xs text-white/60 mt-0.5">
                {data.overallScore >= 75 ? 'Investor Ready' : 
                 data.overallScore >= 50 ? 'Stark Potential' :
                 data.overallScore >= 25 ? 'Lovande Start' : 'Tidigt Stadium'}
              </p>
            </div>
            <div className="w-14 h-14 flex-shrink-0">
              <CircularProgressbar
                value={data.overallScore}
                text={`${data.overallScore}`}
                styles={buildStyles({
                  textSize: '32px',
                  pathColor: getScoreColor(data.overallScore),
                  textColor: '#fff',
                  trailColor: 'rgba(255, 255, 255, 0.1)',
                })}
              />
            </div>
          </div>
          
          {/* Tab Navigation */}
          <div className="flex gap-1 mt-3">
            {[
              { id: 'overview', label: 'Översikt', icon: '📊' },
              { id: 'details', label: 'Detaljer', icon: '🔍' },
              { id: 'actions', label: 'Åtgärder', icon: '🎯' }
            ].map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id as any)}
                className={`flex-1 py-2 px-2 rounded-lg text-xs font-medium transition-all ${
                  activeTab === tab.id
                    ? 'bg-gradient-to-r from-purple-500 to-pink-500 text-white shadow-lg'
                    : 'bg-white/10 text-white/60'
                }`}
              >
                <span className="block text-lg mb-0.5">{tab.icon}</span>
                <span className="block">{tab.label}</span>
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="px-4 py-6">
        {activeTab === 'overview' && (
          <div className="space-y-4">
            {/* Quick Summary */}
            <div className="bg-white/5 rounded-2xl p-6 border border-white/10">
              <h2 className="text-lg font-bold text-white mb-3">Sammanfattning</h2>
              <div className="space-y-3">
                <div className="flex justify-between">
                  <span className="text-white/60">Status</span>
                  <span className="text-white font-semibold">
                    {data.overallScore >= 75 ? 'Investor Ready' : 'Stark Potential'}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span className="text-white/60">Starkaste område</span>
                  <span className="text-white font-semibold">Traction & KPIs</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-white/60">Fokusområde</span>
                  <span className="text-white font-semibold">Finansiell hälsa</span>
                </div>
              </div>
            </div>

            {/* Category Cards */}
            <div className="grid grid-cols-2 gap-3">
              {categories.slice(0, 6).map(([key, category]: [string, any]) => (
                <div
                  key={key}
                  className="bg-white/5 rounded-xl p-4 border border-white/10"
                >
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-2xl">{getScoreEmoji(category.score)}</span>
                    <span className="text-xl font-bold text-white">{category.score}</span>
                  </div>
                  <p className="text-xs text-white/80 font-medium">{category.label}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        {activeTab === 'details' && (
          <div className="space-y-4">
            {categories.map(([key, category]: [string, any]) => (
              <div key={key} className="bg-white/5 rounded-2xl border border-white/10 overflow-hidden">
                <button
                  onClick={() => setExpandedCategory(expandedCategory === key ? null : key)}
                  className="w-full p-4 flex items-center justify-between"
                >
                  <div className="flex items-center gap-3">
                    <span className="text-2xl">{getScoreEmoji(category.score)}</span>
                    <div className="text-left">
                      <h3 className="font-semibold text-white">{category.label}</h3>
                      <p className="text-xs text-white/60">{category.description}</p>
                    </div>
                  </div>
                  <svg 
                    className={`w-5 h-5 text-white/60 transition-transform ${expandedCategory === key ? 'rotate-180' : ''}`}
                    fill="none" 
                    stroke="currentColor" 
                    viewBox="0 0 24 24"
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                  </svg>
                </button>
                
                {expandedCategory === key && (
                  <div className="px-4 pb-4 space-y-3">
                    {category.insights?.map((insight: string, idx: number) => (
                      <div key={idx} className="bg-white/5 rounded-lg p-3">
                        <p className="text-sm text-white/90">{insight}</p>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}

        {activeTab === 'actions' && (
          <div className="space-y-6">
            <div className="bg-gradient-to-r from-purple-600/20 to-pink-600/20 rounded-2xl p-4 border border-purple-500/50">
              <h2 className="text-lg font-bold text-white mb-2">🎯 Dina nästa steg</h2>
              <p className="text-sm text-white/80">
                Konkreta åtgärder som ökar dina chanser att få finansiering
              </p>
            </div>

            {/* Top 3 Priority Actions */}
            <ActionableInsights 
              insights={[
                ...getActionableInsights('problemSolution'),
                ...getActionableInsights('unitEconomics'),
                ...getActionableInsights('marketTiming')
              ].slice(0, 3)}
            />
          </div>
        )}
      </div>

      {/* Mobile CTA */}
      <div className="fixed bottom-0 left-0 right-0 p-4 bg-slate-900/95 backdrop-blur-lg border-t border-white/10">
        <button className="w-full py-3 bg-gradient-to-r from-purple-500 to-pink-500 text-white font-semibold rounded-xl">
          Ladda ner fullständig rapport
        </button>
      </div>
    </div>
  );
} 