'use client';
import React, { useState, useEffect } from 'react';
import { CircularProgressbar, buildStyles } from 'react-circular-progressbar';
import 'react-circular-progressbar/dist/styles.css';
import ActionableInsights from './ActionableInsights';

const getScoreEmoji = (score: number) => {
  if (score >= 75) return '🚀';
  if (score >= 50) return '⭐';
  if (score >= 25) return '💡';
  return '🔨';
};

const getScoreColor = (score: number) => {
  if (score >= 75) return '#10B981';
  if (score >= 50) return '#F59E0B';
  if (score >= 25) return '#EF4444';
  return '#6B7280';
};

const getActionableInsights = (category: any) => {
  // This would be generated by AI based on the actual scores
  const insightMaps: Record<string, any[]> = {
    problemSolution: [
      {
        title: 'Quantify customer pain in monetary terms',
        impact: 'high',
        timeframe: '1-2 weeks',
        description: 'Your solution addresses a problem but lacks concrete data on what it costs the customer today.',
        implementation: [
          'Interview 10 existing customers about their time usage',
          'Calculate hourly cost × number of hours = annual cost',
          'Document 3-5 concrete examples with company names',
          'Create an "ROI calculator" for sales materials'
        ],
        expectedResult: 'Increase conversion by 30-40% by showing "Save $50,000/year" instead of "Save time"',
        investorPerspective: 'Investors want to see that you understand customer economics in depth. Numbers > feelings.'
      }
    ],
    marketTiming: [
      {
        title: 'Connect your solution to macro trends',
        impact: 'medium',
        timeframe: '1 week',
        description: 'The market is growing but your connection to driving trends is unclear.',
        implementation: [
          'List 3 macro trends driving your market (AI, regulation, etc)',
          'Find 2-3 credible sources per trend (Gartner, McKinsey)',
          'Create a "Why Now" slide with timeline',
          'Connect each trend to your solution specifically'
        ],
        expectedResult: 'Investors understand why this is the right timing and not just "nice to have"',
        investorPerspective: 'We look for companies riding waves, not trying to create them.'
      }
    ],
    unitEconomics: [
      {
        title: 'Optimize CAC through product-led growth',
        impact: 'high',
        timeframe: '3-6 months',
        description: 'Your CAC of €1000 can be halved with the right strategy.',
        implementation: [
          'Build a free "light version" with limitations',
          'Create viral loop: each user invites 2 colleagues',
          'Automate onboarding with product tours',
          'Measure and optimize each step in the activation flow'
        ],
        expectedResult: 'Lower CAC to €500, giving LTV:CAC 8:1 and enabling aggressive expansion',
        investorPerspective: 'Companies with CAC < €500 get 3x higher valuation multiples in Series A.'
      }
    ]
  };

  return insightMaps[category] || [];
};

export default function EnhancedMobileResult({ data }: { data: any }) {
  const [activeTab, setActiveTab] = useState<'overview' | 'details' | 'actions'>('overview');
  const [expandedCategory, setExpandedCategory] = useState<string | null>(null);

  const categories = Object.entries(data.categories);

  // Hide navbar on this page
  useEffect(() => {
    const navbar = document.querySelector('[data-navbar]') as HTMLElement;
    const main = document.querySelector('main') as HTMLElement;
    
    if (navbar) {
      navbar.style.display = 'none';
    }
    
    if (main) {
      main.style.paddingTop = '0';
    }
    
    // Cleanup - show navbar and restore padding when component unmounts
    return () => {
      if (navbar) {
        navbar.style.display = '';
      }
      if (main) {
        main.style.paddingTop = '';
      }
    };
  }, []);

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900/10 to-slate-900">
      {/* Top Header with Score and Navigation */}
      <div className="bg-slate-900/95 backdrop-blur-lg border-b border-white/10 px-4 py-4">
        <div className="flex items-center justify-between mb-4">
          <div className="flex-1">
            <h1 className="text-xl font-bold text-white">Investment Analysis</h1>
            <p className="text-sm text-white/70 mt-1">
              {data.overallScore >= 75 ? 'Investor Ready' : 
                 data.overallScore >= 50 ? 'Strong Potential' :
                 data.overallScore >= 25 ? 'Promising Start' : 'Early Stage'}
            </p>
          </div>
          <div className="w-16 h-16 flex-shrink-0">
            <CircularProgressbar
              value={data.overallScore}
              text={`${data.overallScore}`}
              styles={buildStyles({
                textSize: '28px',
                pathColor: getScoreColor(data.overallScore),
                textColor: '#fff',
                trailColor: 'rgba(255, 255, 255, 0.1)',
              })}
            />
          </div>
        </div>
        
        {/* Tab Navigation */}
        <div className="flex gap-1">
          {[
            { id: 'overview', label: 'Översikt', icon: '📊' },
            { id: 'details', label: 'Detaljer', icon: '🔍' },
            { id: 'actions', label: 'Åtgärder', icon: '🎯' }
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`flex-1 py-3 px-2 rounded-xl text-xs font-medium transition-all ${
                activeTab === tab.id
                  ? 'bg-gradient-to-r from-purple-500 to-pink-500 text-white shadow-lg'
                  : 'bg-white/10 text-white/70 hover:bg-white/20'
              }`}
            >
              <div className="flex flex-col items-center gap-1">
                <span className="text-lg">{tab.icon}</span>
                <span>{tab.label}</span>
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* Content Area */}
      <div className="px-4 py-6">
        {activeTab === 'overview' && (
          <div className="space-y-4">
            {/* Quick Summary */}
            <div className="bg-white/5 rounded-2xl p-6 border border-white/10">
              <h2 className="text-lg font-bold text-white mb-3">Sammanfattning</h2>
              <div className="space-y-3">
                <div className="flex justify-between">
                  <span className="text-white/60">Status</span>
                  <span className="text-white font-semibold">
                    {data.overallScore >= 75 ? 'Investor Ready' : 'Stark Potential'}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span className="text-white/60">Starkaste område</span>
                  <span className="text-white font-semibold">Traction & KPIs</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-white/60">Fokusområde</span>
                  <span className="text-white font-semibold">Finansiell hälsa</span>
                </div>
              </div>
            </div>

            {/* Category Cards */}
            <div className="grid grid-cols-2 gap-3">
              {categories.slice(0, 6).map(([key, category]: [string, any]) => (
                <div
                  key={key}
                  className="bg-white/5 rounded-xl p-4 border border-white/10"
                >
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-2xl">{getScoreEmoji(category.score)}</span>
                    <span className="text-xl font-bold text-white">{category.score}</span>
                  </div>
                  <p className="text-xs text-white/80 font-medium">{category.label}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        {activeTab === 'details' && (
          <div className="space-y-4">
            {categories.map(([key, category]: [string, any]) => (
              <div key={key} className="bg-white/5 rounded-2xl border border-white/10 overflow-hidden">
                <button
                  onClick={() => setExpandedCategory(expandedCategory === key ? null : key)}
                  className="w-full p-4 flex items-center justify-between"
                >
                  <div className="flex items-center gap-3">
                    <span className="text-2xl">{getScoreEmoji(category.score)}</span>
                    <div className="text-left">
                      <h3 className="font-semibold text-white">{category.label}</h3>
                      <p className="text-xs text-white/60">{category.description}</p>
                    </div>
                  </div>
                  <svg 
                    className={`w-5 h-5 text-white/60 transition-transform ${expandedCategory === key ? 'rotate-180' : ''}`}
                    fill="none" 
                    stroke="currentColor" 
                    viewBox="0 0 24 24"
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                  </svg>
                </button>
                
                {expandedCategory === key && (
                  <div className="px-4 pb-4 space-y-3">
                    {category.insights?.map((insight: string, idx: number) => (
                      <div key={idx} className="bg-white/5 rounded-lg p-3">
                        <p className="text-sm text-white/90">{insight}</p>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}

        {activeTab === 'actions' && (
          <div className="space-y-6">
            <div className="bg-gradient-to-r from-purple-600/20 to-pink-600/20 rounded-2xl p-4 border border-purple-500/50">
              <h2 className="text-lg font-bold text-white mb-2">🎯 Your next steps</h2>
              <p className="text-sm text-white/80">
                Concrete actions that increase your chances of getting funding
              </p>
            </div>

            {/* Top 3 Priority Actions */}
            <ActionableInsights 
              insights={[
                ...getActionableInsights('problemSolution'),
                ...getActionableInsights('unitEconomics'),
                ...getActionableInsights('marketTiming')
              ].slice(0, 3)}
            />
          </div>
        )}
      </div>

      {/* Deep Analysis CTA - Mobile */}
      <div className="p-4 mb-20">
        <div className="bg-gradient-to-r from-blue-600/20 to-purple-600/20 rounded-2xl p-6 border border-blue-500/50">
          <h3 className="text-lg font-bold text-white mb-3">🧠 Want Even More Specific Advice?</h3>
          <p className="text-white/80 mb-4 text-sm">
            Get ultra-specific, hands-on recommendations. Answer 8 focused questions for personalized insights.
          </p>
          <button 
            onClick={() => window.location.href = '/deep-analysis-wizard'}
            className="w-full py-3 bg-gradient-to-r from-blue-500 to-purple-500 text-white font-semibold rounded-xl hover:shadow-lg transition-all"
          >
            🎯 Get Deep Analysis
          </button>
        </div>
      </div>

      {/* Mobile CTA */}
      <div className="fixed bottom-0 left-0 right-0 p-4 bg-slate-900/95 backdrop-blur-lg border-t border-white/10">
        <button className="w-full py-3 bg-gradient-to-r from-purple-500 to-pink-500 text-white font-semibold rounded-xl">
          Download complete report
        </button>
      </div>
    </div>
  );
} 